title: Sage 50 Canada Docs
description: Practical checklists, setup guides, and workflows for Sage 50 (Canadian
  Edition).
baseurl: /sage50-canada-docs
url: https://ledger.fromgravelhill.ca
remote_theme: just-the-docs/just-the-docs
search_enabled: true
aux_links:
  Main Site (ledger.fromgravelhill.ca): https://ledger.fromgravelhill.ca
color_scheme: nil
plugins:
- jekyll-remote-theme
heading_anchors: true
