name: link-check
on:
  schedule:
    - cron: '0 7 * * 1' # Mondays
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--config .lychee.toml --fail-if-empty=false **/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
